### ISSUE TITLE
create HDASApp test case

### ISSUE THREAD

**Issue by ShunLiu-NOAA** [NOAA-EMC/HDASApp#9]
@JingCheng-NOAA You might consider creating a HDASApp test case so that the developers can use the same test case for JEDI development and test. Here is an example of RDASApp[ PR#23](https://github.com/NOAA-EMC/RDASApp/pull/23/files).

**Comment by JingCheng-NOAA** [comment]
Thank for the example. We've discussed yesterday and currently working on preparing the dataset.
